language: go

sudo: false

go:
  - 1.7
  - 1.8
  - tip

go_import_path: dannyvankooten/moneybird-go

before_install:
  - go get github.com/mattn/goveralls

script:
  - go vet ./...
  - go test -v ./... -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=coverage.out
